[project]
name = "MariTracer"
version = "0.0.1"
description = "A toy IR tracer for Python programs"
authors = [
  { name="Mariana Dehghan", email="maedehdehghanam@gmail.com" }
]
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.8"
dependencies = []

[project.urls]
"Homepage" = "https://github.com/maedehdehghanam/MariTracer-Toy-Python-IR-generator-.git"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["MariTracer"]
package-dir = {"" = "src"}
